language: cpp
os:
- linux
branches:
  except:
  - gh_pages
  - master
dist: trusty
addons:
  apt:
    packages:
    - docker
notifications:
  email:
    on_success: change
    on_failure: change
git:
  depth: 15
script:
- "./build.sh"
- chmod +x maxima-x86_64.AppImage
deploy:
  provider: releases
  prerelease: false
  draft: false
  skip_cleanup: true
  api_key:
    secure: U7B0vz9/elEv2JBkoAcXpR4XfWgocg6znGDzkUN9prDGGYENYf5obxA/WHZGoiYEFYaGDZISgmBzTBMxI7HuJcwaDOzw94P7dmgUZvXr9116haZr/yNbfOh6wshxAnCpcGcsekILlqLydS33LNOqPcC/IMVWJPxMJrqZgjcJjaMa2NUWXSuo5OM8RuYHEuj64V3rLfbwq6+xhjZYrAwbJCWSoBXKXBRYOPliKbRn0Yqbw1XTahCEklQgtaG5m4MUrjsR7krIhgTTKiyV0vY4GprLra9Aioh/EpWOeoCu9s7vUX+Lmiovj1LUsZ8LRrlExvqDpc/eJAJfovYVciPdgHQPvssfnUL2kkC2vMZY9UGz1PBMyco5pWaAVEcMHaexS9fFqbcNst3+bjomG12HbrG0BOyOb0KW6+/SlgLQRvBrMg1BaIkDYjffxLyRrHLCWWE79uxcSb3qXeAo43I2d3quF5VHX1F89YUGJgO0uehYopDXZ/tqFxucn9eWgvyVAqZl8D9mwJf9fcZdU+IjaE5jmh1qYBabHFVP41le+LBUUgUd1dECJi+mef8Obg3nEMQ4QhKnYPqzNp1C07fcV1hU4OoX1C+BkDfbmN/U2h9Ac2PM1x2FRreUAQ9Cfi6Ln4hGNxJbiLz25yI/kqgWAU1jZiRB64HAtGe/S0SFe4o=
  file: maxima-x86_64.AppImage
  on:
    repo: wxMaxima-developers/docker-maxima
    tags: true
    all_branches: true
